export enum STATUS {
  IDLE = 'IDLE',
  READ_START = 'READ_START',
  READ_END = 'READ_END',
  SAVE_START = 'SAVE_START',
  SAVE_END = 'SAVE_END',
  DELETE_START = 'DELETE_START',
  DELETE_END = 'DELETE_END',
  CANCELLED = 'CANCELLED',
  ERROR = 'ERROR'
}
